# [Info]
site_name: Practical_Skills_23Fall # 左上角的标题
site_url: https://ps_23fall.thorin215-wang.com 
site_author: Thorin
site_description: Practical_Skills_23Fall

# [Extra]
extra_css:
  - stylesheets/basic.css
  - stylesheets/admonition.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.css

# [UI]
## [top]
theme:
  name: material
  # font:
  #   text: Source Sans Pro
  #   code: Source Code Pro
  features: 
    - navigation.instant
    - navigation.tracking
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github


  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: white
      accent: pink

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: blue grey
      accent: pink

# edit_uri: edit/main/docs # 编辑按钮跳转的链接

## [top-right corner]
repo_url: https://github.com/Thorin215/PS_23Fall # 右上角点击跳转的链接
repo_name: Thorin215/PS_23Fall # 右上角的名字
## [bottom-left corner]
copyright: Copyright &copy; 2023 Thorin # 左下角的版权声明
## [bottom-right corner]

extra:
  social: # icons
    - icon: fontawesome/brands/github
      link: https://github.com/Thorin215/
      name: GitHub | charleschile

# [Navigation]
nav:
  - Home:
    - index.md

  - PraticalSkill_23fall:
    - LEC1:Shell and Linux:
      - PraticalSkill/Lec1.md
    - LEC2:Markdown:
      - PraticalSkill/Lec2.md
    - LEC3:Latex:
      - PraticalSkill/Lec3.md

  - CTF:
    - BasicKnowledge:
      - CTF/Basic.md
    - SomethingInteresting:
      - CTF/Security.md
  
  - Tool:
    - Tool/index.md
    - HexoBlog:
      - Tool/Hexo/h1.md
    - MkDocs-Material:
      - Tool/mkdocs/MkDocs Material.md
      - Tool/mkdocs/Online personal notebook plan.md
      - Tool/mkdocs/MkDocs美化.md
    - MacBook:
      - Tool/mac/remacbook.md
      - Tool/mac/troubleshooting.md
    - MIT Missing Semester:
      - Tool/MIT/missing_semester.md
    - Systematic review and Meta-analysis:
      - Tool/systematicReview/notes.md
      - Tool/systematicReview/jhu.md
      - Tool/systematicReview/bilibilil.md
    - git:
      - Tool/git/git.md
    - Vim:
      - Tool/vim/vim.md
    - sublime text:
      - Tool/sublime/sublime.md
    - Resume:
      - Tool/resume/resume.md

  - DS:
    - Review:
      - DS/fds1.md
  
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: Content
  - tables
  - pymdownx.snippets:
      auto_append:
        - includes/abbr.md
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      # linenums: true
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - meta
  
